name: actions
run-name: Deploy docs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: |
          sudo apt install sshpass
          pip install virtualenv
          virtualenv mkdocs 
          source mkdocs/bin/activate
          pip install -r requirements.txt
      
      - name: Build documentation
        run: |
          ./mkdocs/bin/mkdocs build

      - name: Create gh-pages branch
        run: |
          git branch gh-pages
          git checkout --orphan gh-pages
          git add README.md
          git commit -m "Initial gh-pages commit"
          git push -u origin gh-pages

      - name: Deploy to gh-pages
        run: |
          git checkout gh-pages
          rm -rf *
          cp -r ../site/* .
          git add .
          git commit -m "Deploy site to gh-pages branch"
          git config --global user.email iker.ortiz@dipc.org
          git config --global user.name iortizdeluzu
          git push -u origin gh-pages
