name: actions
run-name: Deploy docs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: |
          sudo apt install sshpass
          pip install virtualenv
          virtualenv mkdocs 
          source mkdocs/bin/activate
          pip install -r requirements.txt
      
      - name: Build documentation
        run: |
          ./mkdocs/bin/mkdocs build
      - name: Log with user
        run: |
          git config --global user.name "iortizdeluzu"
          git config --global user.email iker.ortiz@dipc.org
      - name: Create gh-pages branch
        run: |
          git checkout gh-pages
          git add site
          git commit -m "Initial gh-pages commit"
          git push origin gh-pages

          #      - name: Deploy to gh-pages
          #        run: |
          #          git checkout gh-pages
          #          rm -rf *
          #          cp -r ../site/* .
          #          git add .
          #          git commit -m "Deploy site to gh-pages branch"
          #          git push -u origin gh-pages
