name: seftware-update
run-name: software-update
on: 
  push:
    paths:
      - docs/software
env:
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_SSH_USER: ${{ secrets.REMOTE_SSH_USER }}
  REMOTE_IP: ${{ secrets.REMOTE_IP }}

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: |
          sudo apt install sshpass
          pip install virtualenv
          virtualenv mkdocs 
          source mkdocs/bin/activate
          pip install -r requirements.txt
          pip install --upgrade --force-reinstall mkdocs-material
      
      - name: Build documentation
        run: |
          ./mkdocs/bin/mkdocs build
      - name: Create public and private SSH keys
        run: |
          mkdir ~/.ssh
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
          echo "$SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          chmod 0644 ~/.ssh/id_rsa.pub
      - name: test ssh
        run: |
          ssh "$REMOTE_SSH_USER"@"$REMOTE_IP" 'echo "Hello World !!"'

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
